package commentary.engine;

public enum FootballAction {
	START,WELCOME,INTRODUCE_TEAM,START_PLAY,PASS_INITIATED,PASS_RECEIVED,PASS_TACKLED,
	SHOT,OUT,THROW,THROWING,CORNER,CORNER_TAKING,HEADING,GOALY_CATCH,GOALY_PUNCHES_AWAY,
	GOAL,FOUL
}
